### ISSUE TITLE
Setup configuration for profile and aliases

### ISSUE THREAD

**Issue by belminf** [belminf/yadig#4]
```yaml
profiles:
  $profile1:
    $region1: $alias
    $region2: "" // default to $profile/$region
...
```

**Comment by belminf** [comment]
Implemented but different format:

```yaml
search:
  - alias: personal-east
    profile: personal
    region: us-east-2
  - alias: work-west
    profile: bfworks
    region: us-west-1
```

Checks for it in `~/.config/yadig/config.yaml`
